spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DBNAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true  # System.out에 Hibernate 실행 SQL 남기기
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug  # logger를 통해 Hibernate 실행 SQL 남기기
jasypt:
  encryptor:
    bean: encryptorBean
  key: ${KEY_JASYPT}
jwt:
  # base64로 인코딩된 암호 키, HS512 사용하므로 512bit=64byte 이상의 문자
  secretKey: ${KEY_JWT}
server:
  port: 5000