spring:
  profiles:
    active: local
    include: key
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # OAuth2.0
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize  # 네이버 로그인 요청 uri
            token-uri: https://nid.naver.com/oauth2.0/token  # 토큰을 발급받기 위한 uri
            user-info-uri: https://openapi.naver.com/v1/nid/me  # 유저 정보를 받아오기 위한 uri
            user-name-attribute: response  # 회원 정보를 JSON으로 받을 때 키 이름을 response로 지정
        registration:
          naver:
            client-id: ENC(YmiWvZbo4coLHAeamDPKO8c8PR/Y3XRtIjlCcxp2/bM=)
            client-secret: ENC(jv2N6oEwm+ax8wQo/NfuTZIYLwlkuofS)
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: ${mamoori.url}/callback
            scope:
              - name
              - email
          google:
            client-id: ENC(tpqD/CXkruIDaDpOL4LW8PVVTlTUBjc0QoRlmWYWbFNbqQdtnfEwoj8Gw4tOVjnXRDwc2jz4I/gjj5T01RbTRb4q7jGVHw+4fG+MVarGIRa8daOXcEOrpQ==)
            client-secret: ENC(Ozwi6Xh88nVgMU9or0IeNIPIHmesUCZdwEZ+wBH6DjLbIsIGcDobMS5dMBFPATb5)
            redirect-uri: ${mamoori.url}/callback
            scope: profile, email

  # DevTools
  devtools:
    livereload:
      enabled: true  # 정적 리소스 변화가 있을 때 바로 반영

  # Thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false  # thymeleaf에 대한 캐시를 남기지 않음
    check-template-location: true  # 디렉토리에 파일이 있는지 없는지 체크, 없으면 에러 발생

logging:
  level:
    org.hibernate.sql: debug
  config: classpath:logback-spring.xml
#server:
#  port: 8081